### ISSUE TITLE
Cognito pool run gives error on repeat runs

### ISSUE THREAD

**Issue by bisonbet** [gaiin-platform/amplify-genai-iac#7]
In cognito_pool.tf - the first resource '"aws_cognito_user_pool" "main"' - consistently received an error due to the schema trying to change on each run.  Since scheme is immutable once in place, I added the following:

  lifecycle {
    ignore_changes = [
      schema
      # Add other attributes you want to ignore
    ]
  }

**Comment by karnsab** [comment]
Thanks, this should be resolved. thanks
